services:
  db:
    image: postgres
    ports:
      - 5432:${DB_PORT}
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
